//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using Dos.ORM;

namespace MVCCMS.NET.Model
{
    /// <summary>
    /// 实体类ManagerRole。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("ManagerRole")]
    [Serializable]
    public partial class ManagerRole : Entity
    {
        #region Model
        private int _Id;
        private string _RoleName;
        private bool _IsSystem;
        private int _SortId;
        private int? _DepartmentID;

        /// <summary>
        /// 序列
        /// </summary>
        [DisplayName("序列")]
        public int Id
        {
            get { return _Id; }
            set
            {
                this.OnPropertyValueChange("Id");
                this._Id = value;
            }
        }
        /// <summary>
        /// 角色名称
        /// </summary>
        [DisplayName("角色名称")]
        public string RoleName
        {
            get { return _RoleName; }
            set
            {
                this.OnPropertyValueChange("RoleName");
                this._RoleName = value;
            }
        }
        /// <summary>
        /// 是否内置
        /// </summary>
        [DisplayName("是否内置")]
        public bool IsSystem
        {
            get { return _IsSystem; }
            set
            {
                this.OnPropertyValueChange("IsSystem");
                this._IsSystem = value;
            }
        }
        /// <summary>
        /// 排序
        /// </summary>
        [DisplayName("排序")]
        public int SortId
        {
            get { return _SortId; }
            set
            {
                this.OnPropertyValueChange("SortId");
                this._SortId = value;
            }
        }
        /// <summary>
        /// 部门
        /// </summary>
        [DisplayName("部门")]
        public int? DepartmentID
        {
            get { return _DepartmentID; }
            set
            {
                this.OnPropertyValueChange("DepartmentID");
                this._DepartmentID = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Id,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.Id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Id,
                _.RoleName,
                _.IsSystem,
                _.SortId,
                _.DepartmentID,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Id,
                this._RoleName,
                this._IsSystem,
                this._SortId,
                this._DepartmentID,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*" , "ManagerRole");
            /// <summary>
			/// 序列
			/// </summary>
			public readonly static Field Id = new Field("Id" , "ManagerRole" , "序列");
            /// <summary>
			/// 角色名称
			/// </summary>
			public readonly static Field RoleName = new Field("RoleName" , "ManagerRole" , "角色名称");
            /// <summary>
			/// 是否内置
			/// </summary>
			public readonly static Field IsSystem = new Field("IsSystem" , "ManagerRole" , "是否内置");
            /// <summary>
			/// 排序
			/// </summary>
			public readonly static Field SortId = new Field("SortId" , "ManagerRole" , "排序");
            /// <summary>
			/// 部门
			/// </summary>
			public readonly static Field DepartmentID = new Field("DepartmentID" , "ManagerRole" , "部门");
        }
        #endregion
    }
}