//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using Dos.ORM;

namespace MVCCMS.NET.Model
{
    /// <summary>
    /// 实体类ManagerRoleValue。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("ManagerRoleValue")]
    [Serializable]
    public partial class ManagerRoleValue : Entity
    {
        #region Model
        private int _Id;
        private int _RoleId;
        private string _ControllerName;
        private string _ActionName;

        /// <summary>
        /// 
        /// </summary>
        public int Id
        {
            get { return _Id; }
            set
            {
                this.OnPropertyValueChange("Id");
                this._Id = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public int RoleId
        {
            get { return _RoleId; }
            set
            {
                this.OnPropertyValueChange("RoleId");
                this._RoleId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ControllerName
        {
            get { return _ControllerName; }
            set
            {
                this.OnPropertyValueChange("ControllerName");
                this._ControllerName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string ActionName
        {
            get { return _ActionName; }
            set
            {
                this.OnPropertyValueChange("ActionName");
                this._ActionName = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Id,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.Id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Id,
                _.RoleId,
                _.ControllerName,
                _.ActionName,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Id,
                this._RoleId,
                this._ControllerName,
                this._ActionName,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*" , "ManagerRoleValue");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field Id = new Field("Id" , "ManagerRoleValue" , "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field RoleId = new Field("RoleId" , "ManagerRoleValue" , "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ControllerName = new Field("ControllerName" , "ManagerRoleValue" , "");
            /// <summary>
			/// 
			/// </summary>
			public readonly static Field ActionName = new Field("ActionName" , "ManagerRoleValue" , "");
        }
        #endregion
    }
}