//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using Dos.ORM;

namespace MVCCMS.NET.Model
{
    /// <summary>
    /// 实体类Manager。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Manager")]
    [Serializable]
    public partial class Manager : Entity
    {
        #region Model
        private int _Id;
        private string _Username;
        private string _Password;
        private string _Nickname;
        private string _Description;
        private bool _IsSystem;
        private int _RoleId;
        private DateTime _AddTime;
        private DateTime _LastLoginTime;
        private bool _IsLock;

        /// <summary>
        /// 序列
        /// </summary>
        [DisplayName("序列")]
        public int Id
        {
            get { return _Id; }
            set
            {
                this.OnPropertyValueChange("Id");
                this._Id = value;
            }
        }
        /// <summary>
        /// 用户名
        /// </summary>
        [DisplayName("用户名")]
        public string Username
        {
            get { return _Username; }
            set
            {
                this.OnPropertyValueChange("Username");
                this._Username = value;
            }
        }
        /// <summary>
        /// 密码
        /// </summary>
        [DisplayName("密码")]
        public string Password
        {
            get { return _Password; }
            set
            {
                this.OnPropertyValueChange("Password");
                this._Password = value;
            }
        }
        /// <summary>
        /// 昵称
        /// </summary>
        [DisplayName("昵称")]
        public string Nickname
        {
            get { return _Nickname; }
            set
            {
                this.OnPropertyValueChange("Nickname");
                this._Nickname = value;
            }
        }
        /// <summary>
        /// 描述
        /// </summary>
        [DisplayName("描述")]
        public string Description
        {
            get { return _Description; }
            set
            {
                this.OnPropertyValueChange("Description");
                this._Description = value;
            }
        }
        /// <summary>
        /// 是否系统内置
        /// </summary>
        [DisplayName("是否系统内置")]
        public bool IsSystem
        {
            get { return _IsSystem; }
            set
            {
                this.OnPropertyValueChange("IsSystem");
                this._IsSystem = value;
            }
        }
        /// <summary>
        /// 权限
        /// </summary>
        [DisplayName("权限")]
        public int RoleId
        {
            get { return _RoleId; }
            set
            {
                this.OnPropertyValueChange("RoleId");
                this._RoleId = value;
            }
        }
        /// <summary>
        /// 添加时间
        /// </summary>
        [DisplayName("添加时间")]
        public DateTime AddTime
        {
            get { return _AddTime; }
            set
            {
                this.OnPropertyValueChange("AddTime");
                this._AddTime = value;
            }
        }
        /// <summary>
        /// 最后登录时间
        /// </summary>
        [DisplayName("最后登录时间")]
        public DateTime LastLoginTime
        {
            get { return _LastLoginTime; }
            set
            {
                this.OnPropertyValueChange("LastLoginTime");
                this._LastLoginTime = value;
            }
        }
        /// <summary>
        /// 是否锁定
        /// </summary>
        [DisplayName("是否锁定")]
        public bool IsLock
        {
            get { return _IsLock; }
            set
            {
                this.OnPropertyValueChange("IsLock");
                this._IsLock = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Id,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.Id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Id,
                _.Username,
                _.Password,
                _.Nickname,
                _.Description,
                _.IsSystem,
                _.RoleId,
                _.AddTime,
                _.LastLoginTime,
                _.IsLock,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Id,
                this._Username,
                this._Password,
                this._Nickname,
                this._Description,
                this._IsSystem,
                this._RoleId,
                this._AddTime,
                this._LastLoginTime,
                this._IsLock,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*" , "Manager");
            /// <summary>
			/// 序列
			/// </summary>
			public readonly static Field Id = new Field("Id" , "Manager" , "序列");
            /// <summary>
			/// 用户名
			/// </summary>
			public readonly static Field Username = new Field("Username" , "Manager" , "用户名");
            /// <summary>
			/// 密码
			/// </summary>
			public readonly static Field Password = new Field("Password" , "Manager" , "密码");
            /// <summary>
			/// 昵称
			/// </summary>
			public readonly static Field Nickname = new Field("Nickname" , "Manager" , "昵称");
            /// <summary>
			/// 描述
			/// </summary>
			public readonly static Field Description = new Field("Description" , "Manager" , "描述");
            /// <summary>
			/// 是否系统内置
			/// </summary>
			public readonly static Field IsSystem = new Field("IsSystem" , "Manager" , "是否系统内置");
            /// <summary>
			/// 权限
			/// </summary>
			public readonly static Field RoleId = new Field("RoleId" , "Manager" , "权限");
            /// <summary>
			/// 添加时间
			/// </summary>
			public readonly static Field AddTime = new Field("AddTime" , "Manager" , "添加时间");
            /// <summary>
			/// 最后登录时间
			/// </summary>
			public readonly static Field LastLoginTime = new Field("LastLoginTime" , "Manager" , "最后登录时间");
            /// <summary>
			/// 是否锁定
			/// </summary>
			public readonly static Field IsLock = new Field("IsLock" , "Manager" , "是否锁定");
        }
        #endregion
    }
}