//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using Dos.ORM;

namespace MVCCMS.NET.Model
{
    /// <summary>
    /// 实体类Navigation。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [Table("Navigation")]
    [Serializable]
    public partial class Navigation : Entity
    {
        #region Model
        private int _Id;
        private string _NavType;
        private string _Name;
        private string _Title;
        private string _SubTitle;
        private string _IconUrl;
        private string _LinkUrl;
        private int _SortId;
        private bool _IsLock;
        private string _Remark;
        private int _ParentId;
        private string _ClassList;
        private int _ClassLayer;
        private string _ActionType;
        private bool _IsSystem;

        /// <summary>
        /// 序列
        /// </summary>
        [DisplayName("序列")]
        public int Id
        {
            get { return _Id; }
            set
            {
                this.OnPropertyValueChange("Id");
                this._Id = value;
            }
        }
        /// <summary>
        /// 类型
        /// </summary>
        [DisplayName("类型")]
        public string NavType
        {
            get { return _NavType; }
            set
            {
                this.OnPropertyValueChange("NavType");
                this._NavType = value;
            }
        }
        /// <summary>
        /// 识别码
        /// </summary>
        [DisplayName("识别码")]
        public string Name
        {
            get { return _Name; }
            set
            {
                this.OnPropertyValueChange("Name");
                this._Name = value;
            }
        }
        /// <summary>
        /// 名称
        /// </summary>
        [DisplayName("名称")]
        public string Title
        {
            get { return _Title; }
            set
            {
                this.OnPropertyValueChange("Title");
                this._Title = value;
            }
        }
        /// <summary>
        /// 短名称
        /// </summary>
        [DisplayName("短名称")]
        public string SubTitle
        {
            get { return _SubTitle; }
            set
            {
                this.OnPropertyValueChange("SubTitle");
                this._SubTitle = value;
            }
        }
        /// <summary>
        /// 图标
        /// </summary>
        [DisplayName("图标")]
        public string IconUrl
        {
            get { return _IconUrl; }
            set
            {
                this.OnPropertyValueChange("IconUrl");
                this._IconUrl = value;
            }
        }
        /// <summary>
        /// 链接地址
        /// </summary>
        [DisplayName("链接地址")]
        public string LinkUrl
        {
            get { return _LinkUrl; }
            set
            {
                this.OnPropertyValueChange("LinkUrl");
                this._LinkUrl = value;
            }
        }
        /// <summary>
        /// 排序
        /// </summary>
        [DisplayName("排序")]
        public int SortId
        {
            get { return _SortId; }
            set
            {
                this.OnPropertyValueChange("SortId");
                this._SortId = value;
            }
        }
        /// <summary>
        /// 是否显示
        /// </summary>
        [DisplayName("是否显示")]
        public bool IsLock
        {
            get { return _IsLock; }
            set
            {
                this.OnPropertyValueChange("IsLock");
                this._IsLock = value;
            }
        }
        /// <summary>
        /// 备注
        /// </summary>
        [DisplayName("备注")]
        public string Remark
        {
            get { return _Remark; }
            set
            {
                this.OnPropertyValueChange("Remark");
                this._Remark = value;
            }
        }
        /// <summary>
        /// 父级
        /// </summary>
        [DisplayName("父级")]
        public int ParentId
        {
            get { return _ParentId; }
            set
            {
                this.OnPropertyValueChange("ParentId");
                this._ParentId = value;
            }
        }
        /// <summary>
        /// 层级
        /// </summary>
        [DisplayName("层级")]
        public string ClassList
        {
            get { return _ClassList; }
            set
            {
                this.OnPropertyValueChange("ClassList");
                this._ClassList = value;
            }
        }
        /// <summary>
        /// 第几层
        /// </summary>
        [DisplayName("第几层")]
        public int ClassLayer
        {
            get { return _ClassLayer; }
            set
            {
                this.OnPropertyValueChange("ClassLayer");
                this._ClassLayer = value;
            }
        }
        /// <summary>
        /// 操作对象
        /// </summary>
        [DisplayName("操作对象")]
        public string ActionType
        {
            get { return _ActionType; }
            set
            {
                this.OnPropertyValueChange("ActionType");
                this._ActionType = value;
            }
        }
        /// <summary>
        /// 是否内置
        /// </summary>
        [DisplayName("是否内置")]
        public bool IsSystem
        {
            get { return _IsSystem; }
            set
            {
                this.OnPropertyValueChange("IsSystem");
                this._IsSystem = value;
            }
        }
        #endregion

        #region Method
        /// <summary>
        /// 获取实体中的主键列
        /// </summary>
        public override Field[] GetPrimaryKeyFields()
        {
            return new Field[] {
                _.Id,
            };
        }
        /// <summary>
        /// 获取实体中的标识列
        /// </summary>
        public override Field GetIdentityField()
        {
            return _.Id;
        }
        /// <summary>
        /// 获取列信息
        /// </summary>
        public override Field[] GetFields()
        {
            return new Field[] {
                _.Id,
                _.NavType,
                _.Name,
                _.Title,
                _.SubTitle,
                _.IconUrl,
                _.LinkUrl,
                _.SortId,
                _.IsLock,
                _.Remark,
                _.ParentId,
                _.ClassList,
                _.ClassLayer,
                _.ActionType,
                _.IsSystem,
            };
        }
        /// <summary>
        /// 获取值信息
        /// </summary>
        public override object[] GetValues()
        {
            return new object[] {
                this._Id,
                this._NavType,
                this._Name,
                this._Title,
                this._SubTitle,
                this._IconUrl,
                this._LinkUrl,
                this._SortId,
                this._IsLock,
                this._Remark,
                this._ParentId,
                this._ClassList,
                this._ClassLayer,
                this._ActionType,
                this._IsSystem,
            };
        }
        /// <summary>
        /// 是否是v1.10.5.6及以上版本实体。
        /// </summary>
        /// <returns></returns>
        public override bool V1_10_5_6_Plus()
        {
            return true;
        }
        #endregion

        #region _Field
        /// <summary>
        /// 字段信息
        /// </summary>
        public class _
        {
            /// <summary>
            /// * 
            /// </summary>
            public readonly static Field All = new Field("*" , "Navigation");
            /// <summary>
			/// 序列
			/// </summary>
			public readonly static Field Id = new Field("Id" , "Navigation" , "序列");
            /// <summary>
			/// 类型
			/// </summary>
			public readonly static Field NavType = new Field("NavType" , "Navigation" , "类型");
            /// <summary>
			/// 识别码
			/// </summary>
			public readonly static Field Name = new Field("Name" , "Navigation" , "识别码");
            /// <summary>
			/// 名称
			/// </summary>
			public readonly static Field Title = new Field("Title" , "Navigation" , "名称");
            /// <summary>
			/// 短名称
			/// </summary>
			public readonly static Field SubTitle = new Field("SubTitle" , "Navigation" , "短名称");
            /// <summary>
			/// 图标
			/// </summary>
			public readonly static Field IconUrl = new Field("IconUrl" , "Navigation" , "图标");
            /// <summary>
			/// 链接地址
			/// </summary>
			public readonly static Field LinkUrl = new Field("LinkUrl" , "Navigation" , "链接地址");
            /// <summary>
			/// 排序
			/// </summary>
			public readonly static Field SortId = new Field("SortId" , "Navigation" , "排序");
            /// <summary>
			/// 是否显示
			/// </summary>
			public readonly static Field IsLock = new Field("IsLock" , "Navigation" , "是否显示");
            /// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark" , "Navigation" , "备注");
            /// <summary>
			/// 父级
			/// </summary>
			public readonly static Field ParentId = new Field("ParentId" , "Navigation" , "父级");
            /// <summary>
			/// 层级
			/// </summary>
			public readonly static Field ClassList = new Field("ClassList" , "Navigation" , "层级");
            /// <summary>
			/// 第几层
			/// </summary>
			public readonly static Field ClassLayer = new Field("ClassLayer" , "Navigation" , "第几层");
            /// <summary>
			/// 操作对象
			/// </summary>
			public readonly static Field ActionType = new Field("ActionType" , "Navigation" , "操作对象");
            /// <summary>
			/// 是否内置
			/// </summary>
			public readonly static Field IsSystem = new Field("IsSystem" , "Navigation" , "是否内置");
        }
        #endregion
    }
}